### ISSUE TITLE
Improvement: Notifications list with analyze

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/presthubot#10]
Would be cool to have the same listing feature but with PR inside notifications

https://developer.github.com/v3/activity/notifications/

**Comment by Progi1984** [comment]
@NeOMakinG Is it OK for you ?
![image](https://user-images.githubusercontent.com/1533248/83854458-05b42580-a717-11ea-97ee-fd3418e9cee6.png)

**Comment by Progi1984** [comment]
:heavy_check_mark:
