### ISSUE TITLE
Specifics requests for the QA team

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/presthubot#12]
The QA team is gathering some data from Github every day, and it would be very nice to have this kind of data fetched automatically every morning.
Here is the data we gather:
- number of PR with the label "Waiting for QA", without the label "Waiting for author", filtered by branch
- number of PR with the label "Waiting for QA" AND with the label "Waiting for author"
- number of PR for Modules

Here are the corresponding filters:
- **PR 177** : `is:open label:1.7.7.x label:"waiting for qa" -label:"Waiting for author"`
- **PR 176** : `is:open label:1.7.6.x label:"waiting for qa" -label:"Waiting for author" `
- **PR develop**  : `is:open label:"waiting for qa" -label:"Waiting for author"` , then substract the number of PR for 177 and 176 (we do this that way so we can include PRs without the `develop` label)
- **PR Modules** : `is:open is:pr label:"Waiting for QA" org:PrestaShop -label:"Waiting for author"`, then substract the number of PR for develop, 177 and 176
- **PR in WFA** : `is:pr label:"Waiting for QA" org:PrestaShop is:open label:"Waiting for author"`  (this commande must be used in GitHub, not in the PrestaShop/PrestaShop repository)

It would be nice to have the difference between the current data and the data from yesterday, by using some kind of data persistency (SQLite for example ?).

Thanks in advance !

**Comment by SimonGrn** [comment]
FYI this is how it looks like currently when done by hand :
![image](https://user-images.githubusercontent.com/49909275/87771006-0bc21980-c820-11ea-9d9c-d0a7e7eec7b7.png)

**Comment by Progi1984** [comment]
@SimonGrn Is it :ok_hand: for you ?

**Comment by SimonGrn** [comment]
It's working as expected, thank you very much !
I close this now.
