### ISSUE TITLE
BUG : Cron fails 

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/presthubot#13]
Cron fails almost every time on `slack:notifier` step, and force us to restart it 5 or 6 times before it works.

exable of failing build : [#179383416](https://travis-ci.com/github/prestashop/presthubot/builds/179383416)

Error displayed : 
![image](https://user-images.githubusercontent.com/48441421/91699306-61564980-eb74-11ea-8295-698f46fd5030.png)

**Comment by Progi1984** [comment]
@boubkerbribri I add a small CB. We should test on a week if it is working.

**Comment by SimonGrn** [comment]
Seems to work more consistently now ? Or maybe you relaunch it every morning I didn't check 🤣

**Comment by Progi1984** [comment]
No, I force relaunch until success.
