### ISSUE TITLE
Modify the request to get PR in WFQA state

### ISSUE THREAD

**Issue by SimonGrn** [PrestaShop/presthubot#16]
Hello,

PR in WFQA must be accounted for only if they don't share another "Waiting for..." label.
So PR with labels 
* "Waiting for PM"
* "Waiting for Dev"
* "Waiting for author"

should be ignored.

This can be done by adding the `-label:"Waiting for Dev"` (for this label specifically) to the command retrieving the data from Github.

This should be done for every request (active branches and modules).

Thank you !

**Comment by Progi1984** [comment]
@SimonGrn Les PR "waiting for dev" & "waiting for author" sont déjà exclus de la recherche WFQA : 

https://github.com/PrestaShop/presthubot/blob/master/src/App/Service/Github/Query.php#L29-L32

**Comment by SimonGrn** [comment]
Yes I know, I just wanted to summarize, and it would be nice to include "Waiting for PM" too 😄

**Comment by Progi1984** [comment]
@SimonGrn Fixed.

**Comment by SD1982** [comment]
Hi @Progi1984 it seems that the "waiting for dev" PR are still retrieved by presthubot
![image](https://user-images.githubusercontent.com/40635814/104319004-85417880-54e0-11eb-8b46-5c54f82a44e4.png)

**Comment by Progi1984** [comment]
@SD1982 Woot ! Label names have been changed. :(

**Comment by Progi1984** [comment]
```
Ajout de majuscules à :Waiting for author
Waiting for dev
Waiting for PM
Waiting for QA
Waiting for rebase
Waiting for UX
Waiting for wordingUpdate de :‘< 1.6’ en ‘< 1.7.x’
‘Nice to have’ en ‘Nice-to-have’
‘Missing basic information required’ en ‘Missing information’
‘To Do’ en ‘To do’
‘Epic’ en ‘EPIC’ (modifié) 
```

**Comment by Progi1984** [comment]
Corrigé.
