### ISSUE TITLE
I want to Add a CONTRIBUITION,md file

### ISSUE THREAD

**Issue by taqui-786** [PrestaShop/presthubot#174]
I **propose** adding a step-by-step contribution guide to contribuition.md. This guide will streamline onboarding for new contributors, enhance collaboration, and ensure consistent contributions. It will serve as a valuable resource, fostering a more inclusive and productive open-source community.

**Please Assign me**

**Comment by kpodemski** [comment]
Hello @taqui-786 

I'm sorry for not getting back to you sooner. This repository is a very specific tool used mostly by project maintainers, at the moment we don't need anything more than what is already available in Readme.md.
