### ISSUE TITLE
remove from the pr module counter, pr in wfqa from archived modules

### ISSUE THREAD

**Issue by sarahdib** [PrestaShop/presthubot#20]
remove from the pr module counter, the pr in wfqa from the archived modules
<img width="842" alt="Capture d’écran 2021-02-03 à 17 14 22" src="https://user-images.githubusercontent.com/3034677/106775311-4ae07c80-6643-11eb-88cf-3d6e26fb45ae.png">

**Comment by Progi1984** [comment]
@sarahdib It's fixed.
