### ISSUE TITLE
Wrong link and Result on slack

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/presthubot#21]
When publishing result on 22/02/2021, the link for develop report is not correct.

Actual Link: https://nightly.prestashop.com/report/914 (for autoupgrade)

![image](https://user-images.githubusercontent.com/48441421/108682500-abe7cb80-74f0-11eb-81aa-4b8ba69e0c96.png)

**Comment by Progi1984** [comment]
@boubkerbribri That should be fixed. I don't check the campaign (only date & version).
