### ISSUE TITLE
[Slack QA] Add Link PR 178x

### ISSUE THREAD

**Issue by boubkerbribri** [PrestaShop/presthubot#27]
Now that the 1.7.8.x branch is created, We should remove lin `PR 1.7.6.x` and replace it with new link`PR 1.7.8.x`.

![image](https://user-images.githubusercontent.com/48441421/115558569-2ba4d300-a2b3-11eb-85d9-350ccc4facf0.png)

**Comment by Progi1984** [comment]
PR #28
