### ISSUE TITLE
Add PR "Blocked" in QA Slack Notification

### ISSUE THREAD

**Issue by Robin-Fischer-PS** [PrestaShop/presthubot#42]
Hi there !

QA team would like to have on the daily QA Slack Notification a new info : The PR in status "Blocked".

Just like the PR with labels "Waiting for QA" + "Waiting for author", the PR with labels "Waiting for QA" + "Blocked" should not be counted in the "Ready to test" PR, nor in the "PR 1.7.8.x", "PR develop", "PR Modules" or "PR Specs" counts.

So to summurize, we would like to have : 

1. A new category in the stats : "[PR Blocked](https://github.com/search?q=org%3APrestaShop+archived%3Afalse+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+label%3A%22blocked%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22)", with the following filter : 

`https://github.com/search?q=org%3APrestaShop+archived%3Afalse+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+label%3A%22blocked%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22`

2. The other filters should be (correct me if it's wrong :D ) : 

- [PR 1.7.8.x](https://github.com/search?q=repo%3APrestaShop%2FPrestaShop+is%3Apr+is%3Aopen+base%3A1.7.8.x+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22) : `https://github.com/search?q=repo%3APrestaShop%2FPrestaShop+is%3Apr+is%3Aopen+base%3A1.7.8.x+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22`
- [PR develop](https://github.com/search?q=repo%3APrestaShop%2FPrestaShop+is%3Apr+is%3Aopen+base%3Adevelop+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22) : `https://github.com/search?q=repo%3APrestaShop%2FPrestaShop+is%3Apr+is%3Aopen+base%3Adevelop+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22`
- [PR Modules](https://github.com/search?q=org%3APrestaShop+archived%3Afalse+-repo%3APrestaShop%2FPrestaShop+-repo%3APrestaShop%2Fprestashop-specs+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22) : `https://github.com/search?q=org%3APrestaShop+archived%3Afalse+-repo%3APrestaShop%2FPrestaShop+-repo%3APrestaShop%2Fprestashop-specs+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22`
- [PR Specs](https://github.com/search?q=repo%3APrestaShop%2Fprestashop-specs+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22) : `https://github.com/search?q=repo%3APrestaShop%2Fprestashop-specs+is%3Apr+is%3Aopen+label%3A%22waiting+for+QA%22+-label%3A%22waiting+for+author%22+-label%3A%22waiting+for+dev%22+-label%3A%22waiting+for+PM%22+-label%3A%22blocked%22`

3. And the "Blocked" PR should also not be counted in the "PR Ready to Test" block.

Do you think it's possible ?

Thanks !

**Comment by Progi1984** [comment]
@Robin-Fischer-PS Done in #43

**Comment by Robin-Fischer-PS** [comment]
Thanks a lot !
